# Hardware Profile: Ventoy Key 1 (Primary / ZBook)
KEY_NAME="Ventoy-1-NTFS"
P4_FS="ntfs"
P4_UUID="2C95D29B2DF0500E"
P4_LABEL=""
P4_DEFAULT_MOUNT="/media/ubuntu/2C95D29B2DF0500E"
P4_MOUNT_OPTS="rw,umask=000,uid=1000,gid=1000,force"
ISO_NAME="rescuezilla-2.6.2-64bit.noble.iso"
PERSIST_CONTAINER="rescuezilla-persistence.dat"
PERSIST_LABEL="casper-rw"
