# Hardware Profile: Ventoy Key 2 (SanDisk / ThinkPad)
KEY_NAME="Ventoy-2-FAT32"
P4_FS="vfat"
P4_UUID="C9D1-3C83"
P4_LABEL="SHARED FAT"
P4_DEFAULT_MOUNT="/media/ubuntu/SHARED_FAT"
P4_MOUNT_OPTS="rw,umask=000,uid=1000,gid=1000,iocharset=utf8"
ISO_NAME="rescuezilla-2.6.1-64bit.oracular.iso"
PERSIST_CONTAINER="rescuezilla-persistence.dat"
PERSIST_LABEL="writable"
